// <auto-generated />
namespace BaseSPA.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aggiuntoproprietànomeablog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aggiuntoproprietànomeablog));
        
        string IMigrationMetadata.Id
        {
            get { return "201707170647039_aggiunto-proprietà-nome-a-blog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
