// <auto-generated />
namespace BaseSPA.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class provesulledate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(provesulledate));
        
        string IMigrationMetadata.Id
        {
            get { return "201802191331484_prove-sulle-date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
